# Generated by Django 2.2.28 on 2022-11-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressopbcizhpwu'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressopbcizhpwu',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
